package dao.domain;

public class ExPool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expool.exid
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private Integer exid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expool.title1
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String title1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expool.url
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expool.downloaded
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private Integer downloaded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expool.looked
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private Integer looked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expool.exid
     *
     * @return the value of expool.exid
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public Integer getExid() {
        return exid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expool.exid
     *
     * @param exid the value for expool.exid
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setExid(Integer exid) {
        this.exid = exid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expool.title1
     *
     * @return the value of expool.title1
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getTitle1() {
        return title1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expool.title1
     *
     * @param title1 the value for expool.title1
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setTitle1(String title1) {
        this.title1 = title1 == null ? null : title1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expool.url
     *
     * @return the value of expool.url
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expool.url
     *
     * @param url the value for expool.url
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expool.downloaded
     *
     * @return the value of expool.downloaded
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public Integer getDownloaded() {
        return downloaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expool.downloaded
     *
     * @param downloaded the value for expool.downloaded
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setDownloaded(Integer downloaded) {
        this.downloaded = downloaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expool.looked
     *
     * @return the value of expool.looked
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public Integer getLooked() {
        return looked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expool.looked
     *
     * @param looked the value for expool.looked
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setLooked(Integer looked) {
        this.looked = looked;
    }
}