package dao.domain;

public class MoePool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.postid
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.title1
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String title1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.title2
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String title2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.title3
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String title3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.url
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.absurl
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String absurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.file_path
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.download
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String download;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moepool.absdownload
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    private String absdownload;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.postid
     *
     * @return the value of moepool.postid
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.postid
     *
     * @param postid the value for moepool.postid
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.title1
     *
     * @return the value of moepool.title1
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getTitle1() {
        return title1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.title1
     *
     * @param title1 the value for moepool.title1
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setTitle1(String title1) {
        this.title1 = title1 == null ? null : title1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.title2
     *
     * @return the value of moepool.title2
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getTitle2() {
        return title2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.title2
     *
     * @param title2 the value for moepool.title2
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setTitle2(String title2) {
        this.title2 = title2 == null ? null : title2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.title3
     *
     * @return the value of moepool.title3
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getTitle3() {
        return title3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.title3
     *
     * @param title3 the value for moepool.title3
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setTitle3(String title3) {
        this.title3 = title3 == null ? null : title3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.url
     *
     * @return the value of moepool.url
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.url
     *
     * @param url the value for moepool.url
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.absurl
     *
     * @return the value of moepool.absurl
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getAbsurl() {
        return absurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.absurl
     *
     * @param absurl the value for moepool.absurl
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setAbsurl(String absurl) {
        this.absurl = absurl == null ? null : absurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.file_path
     *
     * @return the value of moepool.file_path
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.file_path
     *
     * @param filePath the value for moepool.file_path
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.download
     *
     * @return the value of moepool.download
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.download
     *
     * @param download the value for moepool.download
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setDownload(String download) {
        this.download = download == null ? null : download.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moepool.absdownload
     *
     * @return the value of moepool.absdownload
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public String getAbsdownload() {
        return absdownload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moepool.absdownload
     *
     * @param absdownload the value for moepool.absdownload
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    public void setAbsdownload(String absdownload) {
        this.absdownload = absdownload == null ? null : absdownload.trim();
    }
}