package dao;

import dao.domain.HcomicPool;
import dao.domain.HcomicPoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HcomicPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    long countByExample(HcomicPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int deleteByExample(HcomicPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int deleteByPrimaryKey(Integer comicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int insert(HcomicPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int insertSelective(HcomicPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    List<HcomicPool> selectByExample(HcomicPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    HcomicPool selectByPrimaryKey(Integer comicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") HcomicPool record, @Param("example") HcomicPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int updateByExample(@Param("record") HcomicPool record, @Param("example") HcomicPoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int updateByPrimaryKeySelective(HcomicPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hcomicpool
     *
     * @mbg.generated Fri Jan 03 17:17:47 CST 2020
     */
    int updateByPrimaryKey(HcomicPool record);
}